//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rex.Tools.Test.DataCheck.Resource.StringTable {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rex.Tools.Test.DataCheck.Resource.StringTable.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   １．指定するフォルダ中のExcelファイルからSQLバッチファイルを一括作成します。
        ///DataCheckTool.exe -M 0 -P &quot;Folder&quot; -T [True|False] [-S &quot;Pattern&quot;] [-B &quot;FileName&quot;]
        ///２．指定する期待データと移行結果を比較します。
        ///DataCheckTool.exe -M 1 -F &quot;期待データファイル&quot; [-O &quot;出力フォルダ&quot;]
        ///
        ///-M [0]                処理モード  0:データインサートバッチ作成  1:データチェック
        ///-P &quot;Folder&quot;           対象ファイルのフォルダ
        ///-T [True|False]       移行先DBかどうか True:移行先　False：移行元
        ///-S &quot;Pattern&quot;          対象ファイルの検索パタン(例：*(移行元).xls?)
        ///-B &quot;Bitch File Name&quot;  他のバッチ処理（ある場合）
        ///-F &quot;期待データ&quot;       期待データのファイルパス　
        ///-O &quot;出力フォルダ&quot;     比較結果報告の出力フォルダ
        ///-H         [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BatchHelp {
            get {
                return ResourceManager.GetString("BatchHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   【{0}】
        ///{1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreatedTableSqlScript {
            get {
                return ResourceManager.GetString("CreatedTableSqlScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SQL Scriptを作成しています... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreatingSqlScript {
            get {
                return ResourceManager.GetString("CreatingSqlScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設計ファイルを読み取りしています... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpenDesignFile {
            get {
                return ResourceManager.GetString("OpenDesignFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProcessFinished {
            get {
                return ResourceManager.GetString("ProcessFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テーブル一覧を読み取りしています... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReadingTableList {
            get {
                return ResourceManager.GetString("ReadingTableList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sheet:{0} Table:{1}作成失敗しました！ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ScriptCreateFailed {
            get {
                return ResourceManager.GetString("ScriptCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   -----------------------Table:{0}【{1}】----------------------------------- に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SqlScriptStart {
            get {
                return ResourceManager.GetString("SqlScriptStart", resourceCulture);
            }
        }
    }
}
