'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.225
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'このクラスは StronglyTypedResourceBuilder クラスが ResGen
    'または Visual Studio のようなツールを使用して自動生成されました。
    'メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    'ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    '''<summary>
    '''  ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SQLViewer.DBAccess.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        '''  現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  SELECT 
        '''NVL(ARGUMENT_NAME,&apos;戻り値&apos;) AS &quot;引数名&quot;,
        '''DATA_TYPE AS &quot;データ型&quot;,
        '''IN_OUT AS &quot;I/O&quot;, 
        '''DEFAULT_VALUE AS &quot;デフォルト値&quot;
        '''FROM 
        '''ALL_ARGUMENTS 
        '''WHERE 
        '''(OWNER= :OWNER)
        '''AND (PACKAGE_NAME IS NULL) 
        '''AND (OBJECT_NAME = :OBJECTNAME) 
        '''ORDER BY
        '''POSITION に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property GetArguement() As String
            Get
                Return ResourceManager.GetString("GetArguement", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  SELECT 
        '''NVL(ARGUMENT_NAME,&apos;ReturnValue&apos;) AS ARGUMENT_NAME,
        '''DATA_TYPE,
        '''IN_OUT, 
        '''DEFAULT_VALUE,
        '''OBJECT_NAME
        '''FROM 
        '''ALL_ARGUMENTS 
        '''WHERE 
        '''(:OWNER IS NULL OR OWNER= :OWNER)
        '''AND (:PACKAGENAME IS NULL OR PACKAGE_NAME = :PACKAGENAME) 
        '''AND (OBJECT_NAME = :OBJECTNAME) 
        '''ORDER BY
        '''POSITION に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property GetArguement2() As String
            Get
                Return ResourceManager.GetString("GetArguement2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  SELECT 
        ''' COLUMN_NAME AS &quot;列名&quot;
        ''',CASE WHEN DATA_TYPE IN(&apos;VARCHAR2&apos;,&apos;CHAR&apos;) THEN DATA_TYPE || &apos;(&apos; || DATA_LENGTH || &apos;)&apos;
        '''WHEN DATA_TYPE=&apos;NUMBER&apos; AND NVL(DATA_PRECISION,0)=0 AND NVL(DATA_SCALE,0)=0 THEN DATA_TYPE
        '''WHEN DATA_TYPE=&apos;NUMBER&apos; THEN DATA_TYPE || &apos;(&apos; || TO_CHAR( DATA_PRECISION) || &apos;,&apos; || TO_CHAR(DATA_SCALE) || &apos;)&apos;
        '''ELSE  DATA_TYPE END AS &quot;データ型&quot;
        '''FROM 
        '''ALL_TAB_COLUMNS 
        '''WHERE 
        '''(OWNER = :OWNER) 
        '''AND (TABLE_NAME = :TABLENAME) 
        '''ORDER BY
        '''OWNER, 
        '''TABLE_NAME, 
        '''COLUMN_ID に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property GetColumns() As String
            Get
                Return ResourceManager.GetString("GetColumns", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  SELECT
        '''dbms_metadata.get_ddl(:OBJTYPE,:OBJNAME,:SCHEMA) AS DDL
        '''FROM DUAL
        ''' に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property GetDDL() As String
            Get
                Return ResourceManager.GetString("GetDDL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  SELECT 
        '''OWNER, 
        '''OBJECT_NAME AS OBJNAME, 
        '''SUBOBJECT_NAME,
        ''' OBJECT_ID,
        '''  DATA_OBJECT_ID, CREATED, LAST_DDL_TIME, TIMESTAMP, STATUS, TEMPORARY,
        '''  GENERATED, 
        '''SECONDARY,
        '''&apos;FN&apos; AS TYPE
        '''FROM ALL_OBJECTS 
        '''WHERE  OBJECT_TYPE = &apos;FUNCTION&apos;
        '''AND (OWNER = :OWNER) に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property GetFunction() As String
            Get
                Return ResourceManager.GetString("GetFunction", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  select 
        '''INDEX_NAME,
        '''COLUMN_NAME
        '''from 
        '''all_ind_columns 
        '''where 
        '''(TABLE_OWNER = :OWNER) 
        '''AND (TABLE_NAME = :TABLENAME) 
        '''order by
        '''INDEX_NAME,
        '''COLUMN_NAME に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property GetIndexes() As String
            Get
                Return ResourceManager.GetString("GetIndexes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  SELECT COUNT(*) FROM ALL_OBJECTS WHERE OWNER = :OWNER に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property GetObjectCount() As String
            Get
                Return ResourceManager.GetString("GetObjectCount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  SELECT 
        '''COUNT(*) NUM
        '''FROM 
        '''ALL_OBJECTS 
        '''WHERE (OWNER= :OWNER) 
        '''AND OBJECT_TYPE = &apos;PACKAGE&apos;
        '''AND OBJECT_NAME= :OBJNAME に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property GetPackage() As String
            Get
                Return ResourceManager.GetString("GetPackage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  SELECT 
        '''OWNER, 
        '''OBJECT_NAME AS OBJNAME
        '''FROM ALL_OBJECTS 
        '''WHERE 
        '''(OWNER= :OWNER ) 
        '''AND OBJECT_TYPE = &apos;PACKAGE BODY&apos;
        ''' に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property GetPackageBodies() As String
            Get
                Return ResourceManager.GetString("GetPackageBodies", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  SELECT 
        '''OWNER, 
        '''OBJECT_NAME AS OBJNAME
        '''FROM 
        '''ALL_OBJECTS 
        '''WHERE (OWNER= :OWNER) 
        '''AND OBJECT_TYPE = &apos;PACKAGE&apos; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property GetPackages() As String
            Get
                Return ResourceManager.GetString("GetPackages", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  SELECT 
        '''SEQUENCE_OWNER AS OWNER, 
        '''SEQUENCE_NAME AS OBJNAME,
        '''MIN_VALUE,
        '''MAX_VALUE,
        '''INCREMENT_BY,
        '''CYCLE_FLAG,
        '''ORDER_FLAG,
        '''CACHE_SIZE,
        '''LAST_NUMBER
        '''FROM 
        '''ALL_SEQUENCES 
        '''WHERE 
        '''(SEQUENCE_OWNER = :OWNER) 
        ''' に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property GetSequence() As String
            Get
                Return ResourceManager.GetString("GetSequence", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  SELECT
        ''' OWNER, 
        ''' OBJECT_NAME AS OBJNAME, 
        ''' SUBOBJECT_NAME,
        '''  OBJECT_ID, 
        ''' DATA_OBJECT_ID, 
        ''' CREATED,
        '''  LAST_DDL_TIME, 
        ''' TIMESTAMP,
        '''  STATUS, 
        ''' TEMPORARY, 
        ''' GENERATED, 
        ''' SECONDARY 
        ''' FROM ALL_OBJECTS 
        ''' WHERE 
        ''' (OWNER= :OWNER OR :OWNER is null) 
        '''  AND OBJECT_TYPE = &apos;PROCEDURE&apos; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property GetStoreProcedure() As String
            Get
                Return ResourceManager.GetString("GetStoreProcedure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  SELECT 
        '''OWNER, 
        '''TABLE_NAME, 
        '''DECODE(OWNER, &apos;SYS&apos;, &apos;System&apos;, &apos;SYSTEM&apos;, &apos;System&apos;, &apos;SYSMAN&apos;, &apos;System&apos;,&apos;CTXSYS&apos;, &apos;System&apos;,&apos;MDSYS&apos;, &apos;System&apos;,&apos;OLAPSYS&apos;, &apos;System&apos;, &apos;ORDSYS&apos;, &apos;System&apos;,&apos;OUTLN&apos;, &apos;System&apos;, &apos;WKSYS&apos;, &apos;System&apos;,&apos;WMSYS&apos;, &apos;System&apos;,&apos;XDB&apos;, &apos;System&apos;,&apos;ORDPLUGINS&apos;, &apos;System&apos;,&apos;User&apos;) AS Type 
        '''FROM ALL_TABLES
        '''WHERE (OWNER=:OWNER or :OWNER IS NULL) 
        '''ORDER BY OWNER, TABLE_NAME に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property GetTables() As String
            Get
                Return ResourceManager.GetString("GetTables", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  SELECT * FROM 
        '''ALL_VIEWS 
        '''WHERE 
        '''(OWNER = :OWNER OR :OWNER is null) 
        '''ORDER BY
        '''OWNER,
        '''VIEW_NAME に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property GetViews() As String
            Get
                Return ResourceManager.GetString("GetViews", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
