SELECT 
OWNER, 
OBJECT_NAME AS OBJNAME, 
SUBOBJECT_NAME,
 OBJECT_ID,
  DATA_OBJECT_ID, CREATED, LAST_DDL_TIME, TIMESTAMP, STATUS, TEMPORARY,
  GENERATED, 
SECONDARY,
'FN' AS TYPE
FROM ALL_OBJECTS 
WHERE  OBJECT_TYPE = 'FUNCTION'
AND (OWNER = :OWNER)