//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34209
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RJ.Tools.NotesTransfer.Engines.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RJ.Tools.NotesTransfer.Engines.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   &lt;span id=&quot;{0}&quot;&gt;&lt;xsl:value-of select=&quot;@{1}&quot; disable-output-escaping=&quot;yes&quot;/&gt;&lt;/span&gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DispFieldTemplate {
            get {
                return ResourceManager.GetString("DispFieldTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;%@ Page language=&quot;C#&quot; MasterPageFile=&quot;~masterurl/default.master&quot;    Inherits=&quot;Microsoft.SharePoint.WebPartPages.WebPartPage,Microsoft.SharePoint,Version=16.0.0.0,Culture=neutral,PublicKeyToken=71e9bce111e9429c&quot; meta:webpartpageexpansion=&quot;full&quot; meta:progid=&quot;SharePoint.WebPartPage.Document&quot;  %&gt;
        ///&lt;%@ Register Tagprefix=&quot;SharePoint&quot; Namespace=&quot;Microsoft.SharePoint.WebControls&quot; Assembly=&quot;Microsoft.SharePoint, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c&quot; %&gt; &lt;%@ Register Tagprefix=&quot;Utilitie [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DispFormTemplate {
            get {
                return ResourceManager.GetString("DispFormTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;SharePoint:FormField runat=&quot;server&quot; id=&quot;ff{0}{{$Pos}}&quot; ControlMode=&quot;Edit&quot; FieldName=&quot;{1}&quot; __designer:bind=&quot;{{ddwrt:DataBind(&apos;u&apos;,concat(&apos;ff{0}&apos;,$Pos),&apos;Value&apos;,&apos;ValueChanged&apos;,&apos;ID&apos;,ddwrt:EscapeDelims(string(@ID)),&apos;@{1}&apos;)}}&quot;/&gt;
        ///&lt;SharePoint:FieldDescription runat=&quot;server&quot; id=&quot;ff{0}description{{$Pos}}&quot; FieldName=&quot;{1}&quot; ControlMode=&quot;Edit&quot;/&gt;
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EditFieldTemplate {
            get {
                return ResourceManager.GetString("EditFieldTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;%@ Page language=&quot;C#&quot; MasterPageFile=&quot;~masterurl/default.master&quot;    Inherits=&quot;Microsoft.SharePoint.WebPartPages.WebPartPage,Microsoft.SharePoint,Version=16.0.0.0,Culture=neutral,PublicKeyToken=71e9bce111e9429c&quot; meta:webpartpageexpansion=&quot;full&quot; meta:progid=&quot;SharePoint.WebPartPage.Document&quot;  %&gt;
        ///&lt;%@ Register Tagprefix=&quot;SharePoint&quot; Namespace=&quot;Microsoft.SharePoint.WebControls&quot; Assembly=&quot;Microsoft.SharePoint, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c&quot; %&gt; &lt;%@ Register Tagprefix=&quot;Utilitie [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EditFormTemplate {
            get {
                return ResourceManager.GetString("EditFormTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Mappings xmlns=&quot;http://tempuri.org/Mappings.xsd&quot;&gt;
        ///  &lt;!--データベース種別--&gt;
        ///  &lt;DbTypeMap&gt;
        ///    &lt;NotesDbType&gt;DBTYPE_STANDARD&lt;/NotesDbType&gt;
        ///    &lt;SPListType&gt;GenericList&lt;/SPListType&gt;
        ///    &lt;CanConvert&gt;true&lt;/CanConvert&gt;
        ///  &lt;/DbTypeMap&gt;
        ///  &lt;DbTypeMap&gt;
        ///    &lt;NotesDbType&gt;DBTYPE_LIBRARY&lt;/NotesDbType&gt;
        ///    &lt;SPListType&gt;DocumentLibrary&lt;/SPListType&gt;
        ///    &lt;CanConvert&gt;true&lt;/CanConvert&gt;
        ///  &lt;/DbTypeMap&gt;
        ///  &lt;DbTypeMap&gt;
        ///    &lt;NotesDbType&gt;DBTYPE_ADDR_BOOK&lt;/NotesDbType&gt;
        ///    &lt;SPListType&gt;Contac [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mappings {
            get {
                return ResourceManager.GetString("Mappings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;SharePoint:FormField runat=&quot;server&quot; id=&quot;ff{0}{{$Pos}}&quot; ControlMode=&quot;New&quot; FieldName=&quot;{1}&quot; __designer:bind=&quot;{{ddwrt:DataBind(&apos;i&apos;,concat(&apos;ff{0}&apos;,$Pos),&apos;Value&apos;,&apos;ValueChanged&apos;,&apos;ID&apos;,ddwrt:EscapeDelims(string(@ID)),&apos;@{1}&apos;)}}&quot;/&gt;
        ///&lt;SharePoint:FieldDescription runat=&quot;server&quot; id=&quot;ff{0}description{{$Pos}}&quot; FieldName=&quot;{1}&quot; ControlMode=&quot;New&quot;/&gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewFieldTemplate {
            get {
                return ResourceManager.GetString("NewFieldTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;%@ Page language=&quot;C#&quot; MasterPageFile=&quot;~masterurl/default.master&quot;    Inherits=&quot;Microsoft.SharePoint.WebPartPages.WebPartPage,Microsoft.SharePoint,Version=16.0.0.0,Culture=neutral,PublicKeyToken=71e9bce111e9429c&quot; meta:webpartpageexpansion=&quot;full&quot; meta:progid=&quot;SharePoint.WebPartPage.Document&quot;  %&gt;
        ///&lt;%@ Register Tagprefix=&quot;SharePoint&quot; Namespace=&quot;Microsoft.SharePoint.WebControls&quot; Assembly=&quot;Microsoft.SharePoint, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c&quot; %&gt; &lt;%@ Register Tagprefix=&quot;Utilitie [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewFormTemplate {
            get {
                return ResourceManager.GetString("NewFormTemplate", resourceCulture);
            }
        }
    }
}
