//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34209
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RJ.Tools.NotesTransfer.Engines.Notes.Schema {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class XPATHS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XPATHS() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RJ.Tools.NotesTransfer.Engines.Notes.Schema.XPATHS", typeof(XPATHS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   http://www.lotus.com/dxl に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DXL_NAMESPACE {
            get {
                return ResourceManager.GetString("DXL_NAMESPACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   //x:attachmentref に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XPATH_ATTACHMENTREF {
            get {
                return ResourceManager.GetString("XPATH_ATTACHMENTREF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   //x:file[@name=&apos;{0}&apos;] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XPATH_ATTACHMENTREF_SEARCH {
            get {
                return ResourceManager.GetString("XPATH_ATTACHMENTREF_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   //x:item[@name=&apos;IconBitmap&apos;]/x:rawitemdata に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XPATH_DBICON {
            get {
                return ResourceManager.GetString("XPATH_DBICON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   //x:form[@default=&apos;true&apos;] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XPATH_DEFAULT_FORM {
            get {
                return ResourceManager.GetString("XPATH_DEFAULT_FORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ./x:filedata に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XPATH_FILEDATA_NODE {
            get {
                return ResourceManager.GetString("XPATH_FILEDATA_NODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   //x:form[@name=&apos;{0}&apos;] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XPATH_FORM {
            get {
                return ResourceManager.GetString("XPATH_FORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   //x:form[@name=&apos;{0}&apos;]/descendant::x:field に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XPATH_FORM_FIELDS {
            get {
                return ResourceManager.GetString("XPATH_FORM_FIELDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   //x:imageref に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XPATH_IMAGEREF {
            get {
                return ResourceManager.GetString("XPATH_IMAGEREF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   //x:imageresource[@name=&apos;{0}&apos; or contains(@alias,&apos;{0}&apos;)] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XPATH_IMAGEREF_SEARCH {
            get {
                return ResourceManager.GetString("XPATH_IMAGEREF_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ./x:gif | ./x:jpeg | ./x:png に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XPATH_IMG_NODE {
            get {
                return ResourceManager.GetString("XPATH_IMG_NODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   //x:gif | //x:jpeg | //x:png に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XPATH_IMG_RESOURCE {
            get {
                return ResourceManager.GetString("XPATH_IMG_RESOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   //x:form[@name=&apos;{0}&apos;]/descendant::x:pardef/@id に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XPATH_PARDEF_ID {
            get {
                return ResourceManager.GetString("XPATH_PARDEF_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   //x:form[@name=&apos;{0}&apos;]/descendant::x:sharedfieldref に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XPATH_SHARED_FIELDREF {
            get {
                return ResourceManager.GetString("XPATH_SHARED_FIELDREF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   //x:sharedfield/x:field に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XPATH_SHARED_FIELDS {
            get {
                return ResourceManager.GetString("XPATH_SHARED_FIELDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   //x:subform[@name=&apos;{0}&apos; or contains(@alias,&apos;{0}&apos;)] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XPATH_SUBFORM {
            get {
                return ResourceManager.GetString("XPATH_SUBFORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   //x:form[@name=&apos;{0}&apos;]/descendant::x:subformref に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string XPATH_SUBFORMREF {
            get {
                return ResourceManager.GetString("XPATH_SUBFORMREF", resourceCulture);
            }
        }
    }
}
