-- DEST_MASTER
INSERT INTO [DEST_MASTER] ( ID,CATEGORY,SP_TYPE,DISPLAY_NAME) VALUES( 1,N'FIELD',N'Text',N'テキスト')
INSERT INTO [DEST_MASTER] ( ID,CATEGORY,SP_TYPE,DISPLAY_NAME) VALUES( 1,N'LIST',N'GenericList',N'基本リスト')
INSERT INTO [DEST_MASTER] ( ID,CATEGORY,SP_TYPE,DISPLAY_NAME) VALUES( 1,N'VIEW',N'Html',N'標準ビュー ')
INSERT INTO [DEST_MASTER] ( ID,CATEGORY,SP_TYPE,DISPLAY_NAME) VALUES( 2,N'FIELD',N'Note',N'複数行テキスト')
INSERT INTO [DEST_MASTER] ( ID,CATEGORY,SP_TYPE,DISPLAY_NAME) VALUES( 2,N'LIST',N'DocumentLibrary',N'ドキュメントライブラリ')
INSERT INTO [DEST_MASTER] ( ID,CATEGORY,SP_TYPE,DISPLAY_NAME) VALUES( 3,N'FIELD',N'Number',N'数値')
INSERT INTO [DEST_MASTER] ( ID,CATEGORY,SP_TYPE,DISPLAY_NAME) VALUES( 3,N'LIST',N'PictureLibrary',N'画像ライブラリ')
INSERT INTO [DEST_MASTER] ( ID,CATEGORY,SP_TYPE,DISPLAY_NAME) VALUES( 4,N'FIELD',N'DateTime',N'日付と時刻')
INSERT INTO [DEST_MASTER] ( ID,CATEGORY,SP_TYPE,DISPLAY_NAME) VALUES( 5,N'FIELD',N'Currency',N'通貨')
INSERT INTO [DEST_MASTER] ( ID,CATEGORY,SP_TYPE,DISPLAY_NAME) VALUES( 6,N'FIELD',N'Integer',N'整数')
INSERT INTO [DEST_MASTER] ( ID,CATEGORY,SP_TYPE,DISPLAY_NAME) VALUES( 7,N'FIELD',N'File',N'ファイル')
INSERT INTO [DEST_MASTER] ( ID,CATEGORY,SP_TYPE,DISPLAY_NAME) VALUES( 8,N'FIELD',N'Choice',N'選択肢')

