//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.42
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XPBurn {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XPBurn.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   CDRWは既に書き込みています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BurningOrErasing {
            get {
                return ResourceManager.GetString("BurningOrErasing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot add or remove files when the cd burner is burning a CD に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CantChangeFile {
            get {
                return ResourceManager.GetString("CantChangeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The burner is currently in use, either burning or erasing and cannot be ejected に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CantEject {
            get {
                return ResourceManager.GetString("CantEject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recorder type and media type must be CDRW to erase dics に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CantErase {
            get {
                return ResourceManager.GetString("CantErase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Active format must be set to afData in order to retun disc size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CantGetDickSize {
            get {
                return ResourceManager.GetString("CantGetDickSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It&apos;s not possible to get media information while burning or erasing the media. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CantGetMediaInfo {
            get {
                return ResourceManager.GetString("CantGetMediaInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to set drive to {0}. It either does not exist or cannot burn the current format に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CantSetDriver {
            get {
                return ResourceManager.GetString("CantSetDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   afData is not a supported format on this machine に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoafData {
            get {
                return ResourceManager.GetString("NoafData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   afMusic is not a supported format on this machine に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoafMusic {
            get {
                return ResourceManager.GetString("NoafMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   書き込み可能なCDをドライブに挿入してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoCDRDisk {
            get {
                return ResourceManager.GetString("NoCDRDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are no drives on this system which burn the active format に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoDriver {
            get {
                return ResourceManager.GetString("NoDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No XP compatible CDR API present に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoMAPI {
            get {
                return ResourceManager.GetString("NoMAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This API does not support the formats understood by this component に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoSupport {
            get {
                return ResourceManager.GetString("NoSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to select the specified format に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoSupportFormat {
            get {
                return ResourceManager.GetString("NoSupportFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このシステムにCDR/CDRWドライブがありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotCDRW {
            get {
                return ResourceManager.GetString("NotCDRW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File {0} must exist to be burned to a CD&quot; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotExistsFile {
            get {
                return ResourceManager.GetString("NotExistsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Neither argument to AddFile may be emtpy or null strings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotFileName {
            get {
                return ResourceManager.GetString("NotFileName", resourceCulture);
            }
        }
    }
}
