//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassReflect.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"JocrSDKInterface,JocrSDKComponent,HocrSDKInterface,HocrSDKComponent,FormSDKInterface,FormSDKComponent,DocumentSDKInterface,DocumentSDKComponent,DocumentSDKCommon,DenshowNativeCommon,ReportService,ReportServiceProto,DenshowCommon,DenshowDataAccessInterface,DenshowDataAccessComponent,DenshowDataAccessImpl,DenshowBusinessInterface,DenshowBusinessComponent,ReportDefinition,SampleFormsApplication,ReportDefinitionControl,RecogResultCorrection,ReportService,ReportServiceProto")]
        public string OutputNamespaces {
            get {
                return ((string)(this["OutputNamespaces"]));
            }
        }
    }
}
