#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maxz.PoemSystem.Engine.Modules
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="POEMDB")]
	public partial class PoemDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 拡張メソッドの定義
    partial void OnCreated();
    partial void InsertM_PoemType(M_PoemType instance);
    partial void UpdateM_PoemType(M_PoemType instance);
    partial void DeleteM_PoemType(M_PoemType instance);
    partial void InsertM_BookIndex(M_BookIndex instance);
    partial void UpdateM_BookIndex(M_BookIndex instance);
    partial void DeleteM_BookIndex(M_BookIndex instance);
    partial void InsertM_CipaiType(M_CipaiType instance);
    partial void UpdateM_CipaiType(M_CipaiType instance);
    partial void DeleteM_CipaiType(M_CipaiType instance);
    partial void InsertM_Author(M_Author instance);
    partial void UpdateM_Author(M_Author instance);
    partial void DeleteM_Author(M_Author instance);
    partial void InsertM_Cipai(M_Cipai instance);
    partial void UpdateM_Cipai(M_Cipai instance);
    partial void DeleteM_Cipai(M_Cipai instance);
    partial void InsertM_Poem(M_Poem instance);
    partial void UpdateM_Poem(M_Poem instance);
    partial void DeleteM_Poem(M_Poem instance);
    partial void InsertM_PoemImage(M_PoemImage instance);
    partial void UpdateM_PoemImage(M_PoemImage instance);
    partial void DeleteM_PoemImage(M_PoemImage instance);
    partial void InsertM_Poem2(M_Poem2 instance);
    partial void UpdateM_Poem2(M_Poem2 instance);
    partial void DeleteM_Poem2(M_Poem2 instance);
    #endregion
		
		public PoemDBDataContext() : 
				base(global::Maxz.PoemSystem.Engine.Properties.Settings.Default.POEMDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PoemDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PoemDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PoemDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PoemDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<M_PoemType> M_PoemType
		{
			get
			{
				return this.GetTable<M_PoemType>();
			}
		}
		
		public System.Data.Linq.Table<M_BookIndex> M_BookIndex
		{
			get
			{
				return this.GetTable<M_BookIndex>();
			}
		}
		
		public System.Data.Linq.Table<M_CipaiType> M_CipaiType
		{
			get
			{
				return this.GetTable<M_CipaiType>();
			}
		}
		
		public System.Data.Linq.Table<M_Author> M_Author
		{
			get
			{
				return this.GetTable<M_Author>();
			}
		}
		
		public System.Data.Linq.Table<M_Cipai> M_Cipai
		{
			get
			{
				return this.GetTable<M_Cipai>();
			}
		}
		
		public System.Data.Linq.Table<M_Poem> M_Poem
		{
			get
			{
				return this.GetTable<M_Poem>();
			}
		}
		
		public System.Data.Linq.Table<M_PoemImage> M_PoemImage
		{
			get
			{
				return this.GetTable<M_PoemImage>();
			}
		}
		
		public System.Data.Linq.Table<M_Poem2> M_Poem2
		{
			get
			{
				return this.GetTable<M_Poem2>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.M_PoemType")]
	public partial class M_PoemType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _PoemType;
		
		private string _Catrgory;
		
		private string _Description;
		
    #region 拡張メソッドの定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPoemTypeChanging(string value);
    partial void OnPoemTypeChanged();
    partial void OnCatrgoryChanging(string value);
    partial void OnCatrgoryChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    #endregion
		
		public M_PoemType()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PoemType", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string PoemType
		{
			get
			{
				return this._PoemType;
			}
			set
			{
				if ((this._PoemType != value))
				{
					this.OnPoemTypeChanging(value);
					this.SendPropertyChanging();
					this._PoemType = value;
					this.SendPropertyChanged("PoemType");
					this.OnPoemTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Catrgory", DbType="NVarChar(20)")]
		public string Catrgory
		{
			get
			{
				return this._Catrgory;
			}
			set
			{
				if ((this._Catrgory != value))
				{
					this.OnCatrgoryChanging(value);
					this.SendPropertyChanging();
					this._Catrgory = value;
					this.SendPropertyChanged("Catrgory");
					this.OnCatrgoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.M_BookIndex")]
	public partial class M_BookIndex : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _BookNo;
		
		private int _SectionNo;
		
		private string _BookName;
		
		private string _SectionName;
		
    #region 拡張メソッドの定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBookNoChanging(int value);
    partial void OnBookNoChanged();
    partial void OnSectionNoChanging(int value);
    partial void OnSectionNoChanged();
    partial void OnBookNameChanging(string value);
    partial void OnBookNameChanged();
    partial void OnSectionNameChanging(string value);
    partial void OnSectionNameChanged();
    #endregion
		
		public M_BookIndex()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookNo", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int BookNo
		{
			get
			{
				return this._BookNo;
			}
			set
			{
				if ((this._BookNo != value))
				{
					this.OnBookNoChanging(value);
					this.SendPropertyChanging();
					this._BookNo = value;
					this.SendPropertyChanged("BookNo");
					this.OnBookNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SectionNo", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int SectionNo
		{
			get
			{
				return this._SectionNo;
			}
			set
			{
				if ((this._SectionNo != value))
				{
					this.OnSectionNoChanging(value);
					this.SendPropertyChanging();
					this._SectionNo = value;
					this.SendPropertyChanged("SectionNo");
					this.OnSectionNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookName", DbType="NVarChar(50)")]
		public string BookName
		{
			get
			{
				return this._BookName;
			}
			set
			{
				if ((this._BookName != value))
				{
					this.OnBookNameChanging(value);
					this.SendPropertyChanging();
					this._BookName = value;
					this.SendPropertyChanged("BookName");
					this.OnBookNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SectionName", DbType="NVarChar(50)")]
		public string SectionName
		{
			get
			{
				return this._SectionName;
			}
			set
			{
				if ((this._SectionName != value))
				{
					this.OnSectionNameChanging(value);
					this.SendPropertyChanging();
					this._SectionName = value;
					this.SendPropertyChanged("SectionName");
					this.OnSectionNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.M_CipaiType")]
	public partial class M_CipaiType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CipaiType;
		
		private bool _ZeYun;
		
		private bool _Pingyun;
		
		private bool _HuanYun;
		
		private bool _XianYun;
		
		private string _YunBu;
		
    #region 拡張メソッドの定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCipaiTypeChanging(string value);
    partial void OnCipaiTypeChanged();
    partial void OnZeYunChanging(bool value);
    partial void OnZeYunChanged();
    partial void OnPingyunChanging(bool value);
    partial void OnPingyunChanged();
    partial void OnHuanYunChanging(bool value);
    partial void OnHuanYunChanged();
    partial void OnXianYunChanging(bool value);
    partial void OnXianYunChanged();
    partial void OnYunBuChanging(string value);
    partial void OnYunBuChanged();
    #endregion
		
		public M_CipaiType()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CipaiType", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CipaiType
		{
			get
			{
				return this._CipaiType;
			}
			set
			{
				if ((this._CipaiType != value))
				{
					this.OnCipaiTypeChanging(value);
					this.SendPropertyChanging();
					this._CipaiType = value;
					this.SendPropertyChanged("CipaiType");
					this.OnCipaiTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZeYun", DbType="Bit NOT NULL")]
		public bool ZeYun
		{
			get
			{
				return this._ZeYun;
			}
			set
			{
				if ((this._ZeYun != value))
				{
					this.OnZeYunChanging(value);
					this.SendPropertyChanging();
					this._ZeYun = value;
					this.SendPropertyChanged("ZeYun");
					this.OnZeYunChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pingyun", DbType="Bit NOT NULL")]
		public bool Pingyun
		{
			get
			{
				return this._Pingyun;
			}
			set
			{
				if ((this._Pingyun != value))
				{
					this.OnPingyunChanging(value);
					this.SendPropertyChanging();
					this._Pingyun = value;
					this.SendPropertyChanged("Pingyun");
					this.OnPingyunChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HuanYun", DbType="Bit NOT NULL")]
		public bool HuanYun
		{
			get
			{
				return this._HuanYun;
			}
			set
			{
				if ((this._HuanYun != value))
				{
					this.OnHuanYunChanging(value);
					this.SendPropertyChanging();
					this._HuanYun = value;
					this.SendPropertyChanged("HuanYun");
					this.OnHuanYunChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XianYun", DbType="Bit NOT NULL")]
		public bool XianYun
		{
			get
			{
				return this._XianYun;
			}
			set
			{
				if ((this._XianYun != value))
				{
					this.OnXianYunChanging(value);
					this.SendPropertyChanging();
					this._XianYun = value;
					this.SendPropertyChanged("XianYun");
					this.OnXianYunChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YunBu", DbType="NVarChar(10)")]
		public string YunBu
		{
			get
			{
				return this._YunBu;
			}
			set
			{
				if ((this._YunBu != value))
				{
					this.OnYunBuChanging(value);
					this.SendPropertyChanging();
					this._YunBu = value;
					this.SendPropertyChanged("YunBu");
					this.OnYunBuChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.M_Author")]
	public partial class M_Author : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Author;
		
		private string _LastName;
		
		private string _FirstName;
		
		private string _CalledName;
		
		private string _NickName1;
		
		private string _NickName2;
		
		private string _NickName3;
		
		private string _NickName4;
		
		private string _Hometown;
		
		private string _BirthDay;
		
		private string _Biography;
		
		private string _Dynasty;
		
		private string _Comment;
		
    #region 拡張メソッドの定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAuthorChanging(string value);
    partial void OnAuthorChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnCalledNameChanging(string value);
    partial void OnCalledNameChanged();
    partial void OnNickName1Changing(string value);
    partial void OnNickName1Changed();
    partial void OnNickName2Changing(string value);
    partial void OnNickName2Changed();
    partial void OnNickName3Changing(string value);
    partial void OnNickName3Changed();
    partial void OnNickName4Changing(string value);
    partial void OnNickName4Changed();
    partial void OnHometownChanging(string value);
    partial void OnHometownChanged();
    partial void OnBirthDayChanging(string value);
    partial void OnBirthDayChanged();
    partial void OnBiographyChanging(string value);
    partial void OnBiographyChanged();
    partial void OnDynastyChanging(string value);
    partial void OnDynastyChanged();
    partial void OnCommentChanging(string value);
    partial void OnCommentChanged();
    #endregion
		
		public M_Author()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Author", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Author
		{
			get
			{
				return this._Author;
			}
			set
			{
				if ((this._Author != value))
				{
					this.OnAuthorChanging(value);
					this.SendPropertyChanging();
					this._Author = value;
					this.SendPropertyChanged("Author");
					this.OnAuthorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="NVarChar(10)")]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="NVarChar(10)")]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CalledName", DbType="NVarChar(10)")]
		public string CalledName
		{
			get
			{
				return this._CalledName;
			}
			set
			{
				if ((this._CalledName != value))
				{
					this.OnCalledNameChanging(value);
					this.SendPropertyChanging();
					this._CalledName = value;
					this.SendPropertyChanged("CalledName");
					this.OnCalledNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NickName1", DbType="NVarChar(20)")]
		public string NickName1
		{
			get
			{
				return this._NickName1;
			}
			set
			{
				if ((this._NickName1 != value))
				{
					this.OnNickName1Changing(value);
					this.SendPropertyChanging();
					this._NickName1 = value;
					this.SendPropertyChanged("NickName1");
					this.OnNickName1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NickName2", DbType="NVarChar(20)")]
		public string NickName2
		{
			get
			{
				return this._NickName2;
			}
			set
			{
				if ((this._NickName2 != value))
				{
					this.OnNickName2Changing(value);
					this.SendPropertyChanging();
					this._NickName2 = value;
					this.SendPropertyChanged("NickName2");
					this.OnNickName2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NickName3", DbType="NVarChar(20)")]
		public string NickName3
		{
			get
			{
				return this._NickName3;
			}
			set
			{
				if ((this._NickName3 != value))
				{
					this.OnNickName3Changing(value);
					this.SendPropertyChanging();
					this._NickName3 = value;
					this.SendPropertyChanged("NickName3");
					this.OnNickName3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NickName4", DbType="NVarChar(20)")]
		public string NickName4
		{
			get
			{
				return this._NickName4;
			}
			set
			{
				if ((this._NickName4 != value))
				{
					this.OnNickName4Changing(value);
					this.SendPropertyChanging();
					this._NickName4 = value;
					this.SendPropertyChanged("NickName4");
					this.OnNickName4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hometown", DbType="NVarChar(50)")]
		public string Hometown
		{
			get
			{
				return this._Hometown;
			}
			set
			{
				if ((this._Hometown != value))
				{
					this.OnHometownChanging(value);
					this.SendPropertyChanging();
					this._Hometown = value;
					this.SendPropertyChanged("Hometown");
					this.OnHometownChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BirthDay", DbType="NVarChar(50)")]
		public string BirthDay
		{
			get
			{
				return this._BirthDay;
			}
			set
			{
				if ((this._BirthDay != value))
				{
					this.OnBirthDayChanging(value);
					this.SendPropertyChanging();
					this._BirthDay = value;
					this.SendPropertyChanged("BirthDay");
					this.OnBirthDayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Biography", DbType="NVarChar(MAX)")]
		public string Biography
		{
			get
			{
				return this._Biography;
			}
			set
			{
				if ((this._Biography != value))
				{
					this.OnBiographyChanging(value);
					this.SendPropertyChanging();
					this._Biography = value;
					this.SendPropertyChanged("Biography");
					this.OnBiographyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dynasty", DbType="NVarChar(50)")]
		public string Dynasty
		{
			get
			{
				return this._Dynasty;
			}
			set
			{
				if ((this._Dynasty != value))
				{
					this.OnDynastyChanging(value);
					this.SendPropertyChanging();
					this._Dynasty = value;
					this.SendPropertyChanged("Dynasty");
					this.OnDynastyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="NVarChar(MAX)")]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this.OnCommentChanging(value);
					this.SendPropertyChanging();
					this._Comment = value;
					this.SendPropertyChanged("Comment");
					this.OnCommentChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.M_Cipai")]
	public partial class M_Cipai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Cipai;
		
		private string _CipaiType;
		
		private string _OtherNames;
		
		private string _Metrical;
		
		private string _Summary;
		
		private string _Comment;
		
    #region 拡張メソッドの定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCipaiChanging(string value);
    partial void OnCipaiChanged();
    partial void OnCipaiTypeChanging(string value);
    partial void OnCipaiTypeChanged();
    partial void OnOtherNamesChanging(string value);
    partial void OnOtherNamesChanged();
    partial void OnMetricalChanging(string value);
    partial void OnMetricalChanged();
    partial void OnSummaryChanging(string value);
    partial void OnSummaryChanged();
    partial void OnCommentChanging(string value);
    partial void OnCommentChanged();
    #endregion
		
		public M_Cipai()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cipai", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Cipai
		{
			get
			{
				return this._Cipai;
			}
			set
			{
				if ((this._Cipai != value))
				{
					this.OnCipaiChanging(value);
					this.SendPropertyChanging();
					this._Cipai = value;
					this.SendPropertyChanged("Cipai");
					this.OnCipaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CipaiType", DbType="NVarChar(10)")]
		public string CipaiType
		{
			get
			{
				return this._CipaiType;
			}
			set
			{
				if ((this._CipaiType != value))
				{
					this.OnCipaiTypeChanging(value);
					this.SendPropertyChanging();
					this._CipaiType = value;
					this.SendPropertyChanged("CipaiType");
					this.OnCipaiTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OtherNames", DbType="NVarChar(50)")]
		public string OtherNames
		{
			get
			{
				return this._OtherNames;
			}
			set
			{
				if ((this._OtherNames != value))
				{
					this.OnOtherNamesChanging(value);
					this.SendPropertyChanging();
					this._OtherNames = value;
					this.SendPropertyChanged("OtherNames");
					this.OnOtherNamesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Metrical", DbType="NVarChar(MAX)")]
		public string Metrical
		{
			get
			{
				return this._Metrical;
			}
			set
			{
				if ((this._Metrical != value))
				{
					this.OnMetricalChanging(value);
					this.SendPropertyChanging();
					this._Metrical = value;
					this.SendPropertyChanged("Metrical");
					this.OnMetricalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Summary", DbType="NVarChar(MAX)")]
		public string Summary
		{
			get
			{
				return this._Summary;
			}
			set
			{
				if ((this._Summary != value))
				{
					this.OnSummaryChanging(value);
					this.SendPropertyChanging();
					this._Summary = value;
					this.SendPropertyChanged("Summary");
					this.OnSummaryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="NVarChar(MAX)")]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this.OnCommentChanging(value);
					this.SendPropertyChanging();
					this._Comment = value;
					this.SendPropertyChanged("Comment");
					this.OnCommentChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.M_Poem")]
	public partial class M_Poem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID;
		
		private System.Nullable<int> _BookNo;
		
		private System.Nullable<int> _SectionNo;
		
		private System.Nullable<int> _PoemNo;
		
		private string _Title;
		
		private string _Author;
		
		private string _Dynasty;
		
		private string _Foreword;
		
		private string _PoemType;
		
		private string _Cipai;
		
		private string _MainBody;
		
		private string _Comment;
		
    #region 拡張メソッドの定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnBookNoChanging(System.Nullable<int> value);
    partial void OnBookNoChanged();
    partial void OnSectionNoChanging(System.Nullable<int> value);
    partial void OnSectionNoChanged();
    partial void OnPoemNoChanging(System.Nullable<int> value);
    partial void OnPoemNoChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnAuthorChanging(string value);
    partial void OnAuthorChanged();
    partial void OnDynastyChanging(string value);
    partial void OnDynastyChanged();
    partial void OnForewordChanging(string value);
    partial void OnForewordChanged();
    partial void OnPoemTypeChanging(string value);
    partial void OnPoemTypeChanged();
    partial void OnCipaiChanging(string value);
    partial void OnCipaiChanged();
    partial void OnMainBodyChanging(string value);
    partial void OnMainBodyChanged();
    partial void OnCommentChanging(string value);
    partial void OnCommentChanged();
    #endregion
		
		public M_Poem()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookNo", DbType="Int")]
		public System.Nullable<int> BookNo
		{
			get
			{
				return this._BookNo;
			}
			set
			{
				if ((this._BookNo != value))
				{
					this.OnBookNoChanging(value);
					this.SendPropertyChanging();
					this._BookNo = value;
					this.SendPropertyChanged("BookNo");
					this.OnBookNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SectionNo", DbType="Int")]
		public System.Nullable<int> SectionNo
		{
			get
			{
				return this._SectionNo;
			}
			set
			{
				if ((this._SectionNo != value))
				{
					this.OnSectionNoChanging(value);
					this.SendPropertyChanging();
					this._SectionNo = value;
					this.SendPropertyChanged("SectionNo");
					this.OnSectionNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PoemNo", DbType="Int")]
		public System.Nullable<int> PoemNo
		{
			get
			{
				return this._PoemNo;
			}
			set
			{
				if ((this._PoemNo != value))
				{
					this.OnPoemNoChanging(value);
					this.SendPropertyChanging();
					this._PoemNo = value;
					this.SendPropertyChanged("PoemNo");
					this.OnPoemNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(500)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Author", DbType="NVarChar(50)")]
		public string Author
		{
			get
			{
				return this._Author;
			}
			set
			{
				if ((this._Author != value))
				{
					this.OnAuthorChanging(value);
					this.SendPropertyChanging();
					this._Author = value;
					this.SendPropertyChanged("Author");
					this.OnAuthorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dynasty", DbType="NVarChar(50)")]
		public string Dynasty
		{
			get
			{
				return this._Dynasty;
			}
			set
			{
				if ((this._Dynasty != value))
				{
					this.OnDynastyChanging(value);
					this.SendPropertyChanging();
					this._Dynasty = value;
					this.SendPropertyChanged("Dynasty");
					this.OnDynastyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Foreword", DbType="NVarChar(MAX)")]
		public string Foreword
		{
			get
			{
				return this._Foreword;
			}
			set
			{
				if ((this._Foreword != value))
				{
					this.OnForewordChanging(value);
					this.SendPropertyChanging();
					this._Foreword = value;
					this.SendPropertyChanged("Foreword");
					this.OnForewordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PoemType", DbType="NVarChar(50)")]
		public string PoemType
		{
			get
			{
				return this._PoemType;
			}
			set
			{
				if ((this._PoemType != value))
				{
					this.OnPoemTypeChanging(value);
					this.SendPropertyChanging();
					this._PoemType = value;
					this.SendPropertyChanged("PoemType");
					this.OnPoemTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cipai", DbType="NVarChar(50)")]
		public string Cipai
		{
			get
			{
				return this._Cipai;
			}
			set
			{
				if ((this._Cipai != value))
				{
					this.OnCipaiChanging(value);
					this.SendPropertyChanging();
					this._Cipai = value;
					this.SendPropertyChanged("Cipai");
					this.OnCipaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MainBody", DbType="NVarChar(MAX)")]
		public string MainBody
		{
			get
			{
				return this._MainBody;
			}
			set
			{
				if ((this._MainBody != value))
				{
					this.OnMainBodyChanging(value);
					this.SendPropertyChanging();
					this._MainBody = value;
					this.SendPropertyChanged("MainBody");
					this.OnMainBodyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="NVarChar(MAX)")]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this.OnCommentChanging(value);
					this.SendPropertyChanging();
					this._Comment = value;
					this.SendPropertyChanged("Comment");
					this.OnCommentChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.M_PoemImage")]
	public partial class M_PoemImage : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID;
		
		private int _SubID;
		
		private int _ImageId;
		
		private string _Title;
		
		private string _ImageUrl;
		
		private System.Data.Linq.Binary _Image;
		
    #region 拡張メソッドの定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnSubIDChanging(int value);
    partial void OnSubIDChanged();
    partial void OnImageIdChanging(int value);
    partial void OnImageIdChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnImageUrlChanging(string value);
    partial void OnImageUrlChanged();
    partial void OnImageChanging(System.Data.Linq.Binary value);
    partial void OnImageChanged();
    #endregion
		
		public M_PoemImage()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int SubID
		{
			get
			{
				return this._SubID;
			}
			set
			{
				if ((this._SubID != value))
				{
					this.OnSubIDChanging(value);
					this.SendPropertyChanging();
					this._SubID = value;
					this.SendPropertyChanged("SubID");
					this.OnSubIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImageId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ImageId
		{
			get
			{
				return this._ImageId;
			}
			set
			{
				if ((this._ImageId != value))
				{
					this.OnImageIdChanging(value);
					this.SendPropertyChanging();
					this._ImageId = value;
					this.SendPropertyChanged("ImageId");
					this.OnImageIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(200)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImageUrl", DbType="NVarChar(500)")]
		public string ImageUrl
		{
			get
			{
				return this._ImageUrl;
			}
			set
			{
				if ((this._ImageUrl != value))
				{
					this.OnImageUrlChanging(value);
					this.SendPropertyChanging();
					this._ImageUrl = value;
					this.SendPropertyChanged("ImageUrl");
					this.OnImageUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Image", DbType="VarBinary(MAX)", CanBeNull=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Image
		{
			get
			{
				return this._Image;
			}
			set
			{
				if ((this._Image != value))
				{
					this.OnImageChanging(value);
					this.SendPropertyChanging();
					this._Image = value;
					this.SendPropertyChanged("Image");
					this.OnImageChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.M_Poem2")]
	public partial class M_Poem2 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID;
		
		private int _SubID;
		
		private string _Author;
		
		private string _Dynasty;
		
		private string _Title;
		
		private string _Yun;
		
		private string _TitleNote;
		
		private string _MainBody;
		
		private string _Footer;
		
		private string _Comment;
		
		private string _Html;
		
    #region 拡張メソッドの定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnSubIDChanging(int value);
    partial void OnSubIDChanged();
    partial void OnAuthorChanging(string value);
    partial void OnAuthorChanged();
    partial void OnDynastyChanging(string value);
    partial void OnDynastyChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnYunChanging(string value);
    partial void OnYunChanged();
    partial void OnTitleNoteChanging(string value);
    partial void OnTitleNoteChanged();
    partial void OnMainBodyChanging(string value);
    partial void OnMainBodyChanged();
    partial void OnFooterChanging(string value);
    partial void OnFooterChanged();
    partial void OnCommentChanging(string value);
    partial void OnCommentChanged();
    partial void OnHtmlChanging(string value);
    partial void OnHtmlChanged();
    #endregion
		
		public M_Poem2()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int SubID
		{
			get
			{
				return this._SubID;
			}
			set
			{
				if ((this._SubID != value))
				{
					this.OnSubIDChanging(value);
					this.SendPropertyChanging();
					this._SubID = value;
					this.SendPropertyChanged("SubID");
					this.OnSubIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Author", DbType="NVarChar(50)")]
		public string Author
		{
			get
			{
				return this._Author;
			}
			set
			{
				if ((this._Author != value))
				{
					this.OnAuthorChanging(value);
					this.SendPropertyChanging();
					this._Author = value;
					this.SendPropertyChanged("Author");
					this.OnAuthorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dynasty", DbType="NVarChar(50)")]
		public string Dynasty
		{
			get
			{
				return this._Dynasty;
			}
			set
			{
				if ((this._Dynasty != value))
				{
					this.OnDynastyChanging(value);
					this.SendPropertyChanging();
					this._Dynasty = value;
					this.SendPropertyChanged("Dynasty");
					this.OnDynastyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(200)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yun", DbType="NVarChar(10)")]
		public string Yun
		{
			get
			{
				return this._Yun;
			}
			set
			{
				if ((this._Yun != value))
				{
					this.OnYunChanging(value);
					this.SendPropertyChanging();
					this._Yun = value;
					this.SendPropertyChanged("Yun");
					this.OnYunChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TitleNote", DbType="NVarChar(MAX)")]
		public string TitleNote
		{
			get
			{
				return this._TitleNote;
			}
			set
			{
				if ((this._TitleNote != value))
				{
					this.OnTitleNoteChanging(value);
					this.SendPropertyChanging();
					this._TitleNote = value;
					this.SendPropertyChanged("TitleNote");
					this.OnTitleNoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MainBody", DbType="NVarChar(MAX)")]
		public string MainBody
		{
			get
			{
				return this._MainBody;
			}
			set
			{
				if ((this._MainBody != value))
				{
					this.OnMainBodyChanging(value);
					this.SendPropertyChanging();
					this._MainBody = value;
					this.SendPropertyChanged("MainBody");
					this.OnMainBodyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Footer", DbType="NVarChar(MAX)")]
		public string Footer
		{
			get
			{
				return this._Footer;
			}
			set
			{
				if ((this._Footer != value))
				{
					this.OnFooterChanging(value);
					this.SendPropertyChanging();
					this._Footer = value;
					this.SendPropertyChanged("Footer");
					this.OnFooterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="NVarChar(MAX)")]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this.OnCommentChanging(value);
					this.SendPropertyChanging();
					this._Comment = value;
					this.SendPropertyChanged("Comment");
					this.OnCommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Html", DbType="NVarChar(MAX)")]
		public string Html
		{
			get
			{
				return this._Html;
			}
			set
			{
				if ((this._Html != value))
				{
					this.OnHtmlChanging(value);
					this.SendPropertyChanging();
					this._Html = value;
					this.SendPropertyChanged("Html");
					this.OnHtmlChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
